name: Go CI

on:
  push:
    branches: ["main", "codex/**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Verify formatting
        run: |
          fmt_out=$(gofmt -l .)
          if [ -n "$fmt_out" ]; then
            echo "The following files need gofmt:" >&2
            echo "$fmt_out" >&2
            exit 1
          fi

      - name: Go build
        run: go build ./...

      - name: Go test
        run: go test -cover ./...
